import Article from "../models/Article";
import { convertHtmlToArticle } from "./htmlToArticleSchemaConvertor";
import { IArticle } from "../models/Article";

export const htmlGeneratedString = `<div class="container mx-auto px-4 max-w-3xl">
    <section id="introduction">
        <h2 class="text-xl font-bold my-2">The Wonders of Space Exploration: Unlocking the Secrets of the Cosmos</h2>
        <p>Space exploration has been a fascinating topic for centuries, captivating the imagination of humans around the world. From the early astronomers who gazed up at the night sky to the modern-day astronauts who venture into the unknown, space exploration has come a long way. In this article, we will delve into the history of space exploration, its benefits, and the latest advancements in the field. Space exploration is a complex and challenging field that requires the collaboration of scientists, engineers, and technicians from around the world. The benefits of space exploration are numerous, and they include the advancement of scientific knowledge, the development of new technologies, and the improvement of our daily lives. The history of space exploration is a long and fascinating one, with many notable achievements and milestones. The first artificial satellite was launched into space in 1957, and the first human spaceflight took place in 1961. Since then, there have been many notable achievements in space exploration, including the landing of astronauts on the Moon and the establishment of the International Space Station.</p>
        <p>The importance of space exploration cannot be overstated. It has led to numerous breakthroughs in fields such as medicine, transportation, and communication. The benefits of space exploration are not limited to scientific discovery; it also has the potential to improve our daily lives and to inspire future generations of scientists and engineers. As we continue to explore space, we may uncover new secrets of the universe and drive innovation. The history of space exploration is a testament to human ingenuity and the boundless potential of the human spirit. The latest advancements in space exploration are a reminder that the field is constantly evolving and that there are still many exciting developments on the horizon. With the help of private companies and government agencies, space exploration is becoming more accessible and affordable, and it is likely that we will see many new breakthroughs in the coming years.</p>
        <p>The wonders of space exploration are a reminder of the awe-inspiring beauty and complexity of the universe. From the majestic spiral galaxies to the stunning beauty of supernovae, the universe is full of mysteries waiting to be uncovered. As we continue to explore space, we may uncover new secrets of the universe and gain a deeper understanding of the cosmos. The benefits of space exploration are numerous, and they include the advancement of scientific knowledge, the development of new technologies, and the improvement of our daily lives. The history of space exploration is a long and fascinating one, and it is a testament to human ingenuity and the boundless potential of the human spirit. Space exploration has the potential to inspire future generations of scientists and engineers and to drive innovation, and it is likely that we will see many new breakthroughs in the coming years.</p>
        <p>Space exploration is a complex and challenging field that requires the collaboration of scientists, engineers, and technicians from around the world. The benefits of space exploration are numerous, and they include the advancement of scientific knowledge, the development of new technologies, and the improvement of our daily lives. The history of space exploration is a long and fascinating one, with many notable achievements and milestones. The latest advancements in space exploration are a reminder that the field is constantly evolving and that there are still many exciting developments on the horizon. With the help of private companies and government agencies, space exploration is becoming more accessible and affordable, and it is likely that we will see many new breakthroughs in the coming years. The wonders of space exploration are a reminder of the awe-inspiring beauty and complexity of the universe, and they have the potential to inspire future generations of scientists and engineers.</p>
    </section>
    <section id="history">
        <h2 class="text-xl font-bold my-2">A Brief History of Space Exploration</h2>
        <p>The concept of space exploration dates back to ancient civilizations, with philosophers such as Aristotle and Ptolemy proposing the idea of a spherical Earth and a universe with multiple planets. However, it wasn't until the 20th century that space exploration became a reality. On October 4, 1957, the Soviet Union launched Sputnik 1, the first artificial satellite into space, marking the beginning of the space age. The United States soon followed with the launch of Explorer 1, the first American satellite, on January 31, 1958. The first human spaceflight was achieved by Soviet cosmonaut Yuri Gagarin on April 12, 1961, when he orbited the Earth aboard the Vostok 1 spacecraft.</p>
        <p>The United States achieved a major milestone with the Apollo 11 mission, which successfully landed astronauts Neil Armstrong and Buzz Aldrin on the Moon's surface on July 20, 1969. Since then, there have been many notable achievements in space exploration, including the establishment of the International Space Station and the landing of robots on Mars. The history of space exploration is a long and fascinating one, with many notable achievements and milestones. The benefits of space exploration are numerous, and they include the advancement of scientific knowledge, the development of new technologies, and the improvement of our daily lives.</p>  
        <p>Space exploration has the potential to inspire future generations of scientists and engineers and to drive innovation. The latest advancements in space exploration are a reminder that the field is constantly evolving and that there are still many exciting developments on the horizon. With the help of private companies and government agencies, space exploration is becoming more accessible and affordable, and it is likely that we will see many new breakthroughs in the coming years. The wonders of space exploration are a reminder of the awe-inspiring beauty and complexity of the universe, and they have the potential to inspire future generations of scientists and engineers. The history of space exploration is a testament to human ingenuity and the boundless potential of the human spirit.</p>
        <p>The benefits of space exploration are numerous, and they include the advancement of scientific knowledge, the development of new technologies, and the improvement of our daily lives. The history of space exploration is a long and fascinating one, with many notable achievements and milestones. The latest advancements in space exploration are a reminder that the field is constantly evolving and that there are still many exciting developments on the horizon. With the help of private companies and government agencies, space exploration is becoming more accessible and affordable, and it is likely that we will see many new breakthroughs in the coming years. Space exploration has the potential to inspire future generations of scientists and engineers and to drive innovation, and it is a reminder of the awe-inspiring beauty and complexity of the universe.</p>
        <img src="https://t3.ftcdn.net/jpg/06/33/00/42/360_F_633004264_b6ZuRQZYAsZIEYfWdY15EAOiaG4ZJIbn.jpg" class="w-full mr-2 mt-2 mb-1 rounded-xl mx-auto my-2">
        <p class="text-sm text-gray-300 mt-1 mb-2 text-center">Credit: Adobe</p>
    </section>
    <section id="benefits">
        <h2 class="text-xl font-bold my-2">Benefits of Space Exploration</h2>
        <p>Space exploration has numerous benefits, from improving our daily lives to expanding our knowledge of the universe. Some of the benefits include technological advancements, environmental monitoring, scientific discoveries, and inspiration and education. Space exploration has driven the development of new technologies, such as telecommunications, navigation, and medical imaging. Space-based satellites provide critical data on Earth's climate, weather patterns, and natural resources, helping us to better understand and manage our planet.</p>
        <p>Space exploration has led to a greater understanding of the universe, from the discovery of dark matter and dark energy to the detection of exoplanets and the search for life beyond Earth. Space exploration has also inspired generations of students and scientists, promoting interest in STEM fields and fostering a greater appreciation for the wonders of the universe. The benefits of space exploration are not limited to scientific discovery; it also has the potential to improve our daily lives and to inspire future generations of scientists and engineers.</p>
        <p>The latest advancements in space exploration are a reminder that the field is constantly evolving and that there are still many exciting developments on the horizon. With the help of private companies and government agencies, space exploration is becoming more accessible and affordable, and it is likely that we will see many new breakthroughs in the coming years. Space exploration has the potential to drive innovation and to inspire future generations of scientists and engineers. The history of space exploration is a testament to human ingenuity and the boundless potential of the human spirit.</p>
        <p>The benefits of space exploration are numerous, and they include the advancement of scientific knowledge, the development of new technologies, and the improvement of our daily lives. The history of space exploration is a long and fascinating one, with many notable achievements and milestones. The latest advancements in space exploration are a reminder that the field is constantly evolving and that there are still many exciting developments on the horizon. With the help of private companies and government agencies, space exploration is becoming more accessible and affordable, and it is likely that we will see many new breakthroughs in the coming years. The wonders of space exploration are a reminder of the awe-inspiring beauty and complexity of the universe, and they have the potential to inspire future generations of scientists and engineers.</p>
        <p>Space exploration is a complex and challenging field that requires the collaboration of scientists, engineers, and technicians from around the world. The benefits of space exploration are numerous, and they include the advancement of scientific knowledge, the development of new technologies, and the improvement of our daily lives. The history of space exploration is a long and fascinating one, with many notable achievements and milestones. The latest advancements in space exploration are a reminder that the field is constantly evolving and that there are still many exciting developments on the horizon. With the help of private companies and government agencies, space exploration is becoming more accessible and affordable, and it is likely that we will see many new breakthroughs in the coming years.</p>
    </section>
    <section id="latest-advancements">
        <h2 class="text-xl font-bold my-2">Latest Advancements in Space Exploration</h2>
        <p>In recent years, space exploration has experienced a resurgence, with both government agencies and private companies pushing the boundaries of space travel. Some of the latest advancements include reusable rockets, Mars exploration, commercial spaceflight, and international cooperation. Private companies such as SpaceX and Blue Origin have developed reusable rockets, significantly reducing the cost of access to space. NASA's Curiosity Rover has been exploring Mars since 2012, providing valuable insights into the planet's geology and potential habitability.</p>
        <p>Companies such as Virgin Galactic and SpaceX are developing commercial spacecraft capable of carrying passengers to the edge of space and beyond. Space agencies around the world are collaborating on missions such as the International Space Station, demonstrating the power of global cooperation in space exploration. The latest advancements in space exploration are a reminder that the field is constantly evolving and that there are still many exciting developments on the horizon. With the help of private companies and government agencies, space exploration is becoming more accessible and affordable, and it is likely that we will see many new breakthroughs in the coming years.</p>
        <p>Space exploration has the potential to drive innovation and to inspire future generations of scientists and engineers. The history of space exploration is a testament to human ingenuity and the boundless potential of the human spirit. The benefits of space exploration are numerous, and they include the advancement of scientific knowledge, the development of new technologies, and the improvement of our daily lives. The latest advancements in space exploration are a reminder that the field is constantly evolving and that there are still many exciting developments on the horizon.</p>
        <p>The wonders of space exploration are a reminder of the awe-inspiring beauty and complexity of the universe, and they have the potential to inspire future generations of scientists and engineers. Space exploration is a complex and challenging field that requires the collaboration of scientists, engineers, and technicians from around the world. The benefits of space exploration are numerous, and they include the advancement of scientific knowledge, the development of new technologies, and the improvement of our daily lives. The history of space exploration is a long and fascinating one, with many notable achievements and milestones.</p>
        <p>The latest advancements in space exploration are a reminder that the field is constantly evolving and that there are still many exciting developments on the horizon. With the help of private companies and government agencies, space exploration is becoming more accessible and affordable, and it is likely that we will see many new breakthroughs in the coming years. The benefits of space exploration are numerous, and they include the advancement of scientific knowledge, the development of new technologies, and the improvement of our daily lives. Space exploration has the potential to drive innovation and to inspire future generations of scientists and engineers.</p>
    </section>
    <section id="conclusion">
        <h2 class="text-xl font-bold my-2">Conclusion</h2>
        <p>Space exploration is a fascinating and rapidly evolving field, with a rich history, numerous benefits, and exciting advancements on the horizon. As we continue to push the boundaries of space travel, we may uncover new secrets of the universe, drive innovation, and inspire future generations of scientists and explorers. As astronomer Carl Sagan once said, "Somewhere, something incredible is waiting to be known".</p>
        <p>The history of space exploration is a testament to human ingenuity and the boundless potential of the human spirit. The benefits of space exploration are numerous, and they include the advancement of scientific knowledge, the development of new technologies, and the improvement of our daily lives. The latest advancements in space exploration are a reminder that the field is constantly evolving and that there are still many exciting developments on the horizon. With the help of private companies and government agencies, space exploration is becoming more accessible and affordable, and it is likely that we will see many new breakthroughs in the coming years.</p>
    </section>
    <section id="sources">
        <h2 class="text-xl font-bold my-2">Sources</h2>
        <p>Aristotle. (350 BCE). On the Heavens.</p>
        <p>Gagarin, Y. (1961). The First Man in Space.</p>
        <p>NASA. (2022). NASA History. Retrieved from <https://www.nasa.gov/</p>
        <p>NOAA. (2022). National Oceanic and Atmospheric Administration. Retrieved from <https://www.noaa.gov/</p>
        <p>Ptolemy. (150 CE). Almagest.</p>
        <p>Sagan, C. (1980). Cosmos. Random House.</p>
        <p>SpaceX. (2022). SpaceX. Retrieved from <https://www.spacex.com/</p>
        <p>Virgin Galactic. (2022). Virgin Galactic. Retrieved from <https://www.virgingalactic.com/</p>
    </section>
</div>`;

export const testConnversionFromHTMLString = async (
  html_string: string,
  imageUrl: string,
  articleTitle: string
): Promise<IArticle> => {
  const articleData = await convertHtmlToArticle(
    html_string,
    imageUrl,
    articleTitle,
    1,
    0
  );

  return articleData as IArticle;
};
